### ISSUE TITLE
 batch_gaussian_first_lrpt

### ISSUE THREAD

**Issue by zougougou** [zc402/Scoliosis#6]
def batch_gaussian_first_lrpt(self, imgs, batch_labels):
        
        imgs = np.asarray(imgs)
        assert len(imgs.shape) == 3, "(N, h, w)"
        batch_labels = np.array(batch_labels)

        four_corner = np.asarray(self._split_labels_by_corner(batch_labels))
        first_lrpt = four_corner[0:2, :, 0:1, :]  # [tl tr][batch][Joint][xy]
        # first_lrpt = np.transpose(first_lrpt, [1, 0, 2])  # [batch][tl tr][xy]

        lrNHW = np.array([self._batch_gaussian(imgs.shape[1:3], pts) for pts in first_lrpt])
        NHW = np.max(lrNHW, axis=0)

        NCHW = NHW[:, np.newaxis, :, :]  # NCHW.
        return NCHW

Hello, thank you for your code.I'm interested in your work.But I don't quite understand what this code generates.You use PCM to define its return value,Can it be understood as confidence?

**Comment by zc402** [comment]
Correct, this code generate confidence heatmap from label, which is then used to train the PCM network as ground truth.

**Comment by zougougou** [comment]
Thank you for your reply
